# Generated by Django 4.0.3 on 2023-01-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceApp', '0002_useradmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAdmin',
        ),
    ]
