# Generated by Django 4.0.3 on 2023-01-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceApp', '0003_delete_useradmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
